language: dart

os:
 - linux
 - osx
 - windows

dart:
 - stable

install:
 - dart example/download_chromium.dart

dart_task:
 - test: --platform vm
 - dartanalyzer: --fatal-infos --fatal-warnings .
 - dartfmt

branches:
  only: [master]

env:
  global:
    #In travis/docker we need the --no-sandbox flag in chrome
    - CHROME_FORCE_NO_SANDBOX=true

cache:
  directories:
    - $HOME/.pub-cache
