language: dart

os:
 - linux
 - osx
 - windows

dart:
 - stable

# allow headful tests
before_install:
 - "sysctl kernel.unprivileged_userns_clone=1"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

before_script:
 - dart example/download_chromium.dart

dart_task:
 - test: -P ci --platform vm
 - dartanalyzer: --fatal-infos --fatal-warnings .
 - dartfmt: true

jobs:
 include:
  - stage: coverage
    os: osx
    script:
     - pub global activate coverage
     - dart --disable-service-auth-codes --enable-vm-service=8111 --pause-isolates-on-exit test/test_all.dart &
     - pub global run coverage:collect_coverage --port=8111 --out=coverage.json --wait-paused --resume-isolates
     - pub global run coverage:format_coverage --lcov --in=coverage.json --out=lcov.info --packages=.packages --report-on=lib/src

after_success:
 - gem install coveralls-lcov
 - coveralls-lcov lcov.info

branches:
  only: [master]

env:
  global:
    #In travis/docker we need the --no-sandbox flag in chrome
    - CHROME_FORCE_NO_SANDBOX=true

cache:
  directories:
    - $HOME/.pub-cache
