name: puppeteer
description: A high-level API to control headless Chrome over the DevTools Protocol. This is a port of Puppeteer in Dart.
version: 2.25.1
homepage: https://github.com/xvrh/puppeteer-dart

platforms:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  archive: ^3.0.0
  async: ^2.5.0
  collection: ^1.15.0
  http: ^0.13.0
  logging: ^1.0.0
  path: ^1.8.0
  petitparser: ^5.1.0
  pool: ^1.5.0

dev_dependencies:
  analyzer:
  build:
  build_runner:
  crypto:
  dart_style:
  image:
  json_annotation:
  json_serializable:
  lints:
  pub_semver:
  shelf:
  shelf_router:
  shelf_static:
  shelf_web_socket:
  test:
  web_socket_channel:
  yaml:
