name: puppeteer
description: A high-level API to control headless Chrome over the DevTools Protocol. This is a port of Puppeteer in Dart.
version: 1.0.0
homepage: https://github.com/xavierhainaux/chrome_dev_tools
author: Xavier Hainaux <xavier.hainaux@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  archive: ^2.0.0
  async: ^2.2.0
  http: '>=0.9.0 <0.13.0'
  logging: ^0.11.3
  meta: ^1.1.1
  path: '>=1.0.0 <2.0.0'
  petitparser: ^2.2.1
  pool: ^1.4.0

dev_dependencies:
  dart_style: ^1.1.0
  shelf: ^0.7.2
  shelf_static: ^0.2.7
  test:
