# This workflow will update the pinned browsers

name: 'Update the pinned browsers'

permissions: read-all

on:
  schedule:
    # Run everyday at: https://crontab.guru/#0_6_*_*_*.
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - name: Update Chrome to latest stable version
        id: update
        run: |
          dart pub get
          dart tool/update_chrome_revision.dart
      - name: Run various update
        if: ${{ steps.update.outputs.commit }}
        run: |
          dart tool/download_protocol_from_chrome.dart
          dart tool/download_protocol_from_repo.dart
          dart tool/generate_protocol.dart
          dart tool/prepare_submit.dart
      - name: Create Pull Request
        if: ${{ steps.update.outputs.commit }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          commit-message: ${{ steps.update.outputs.commit }}
          title: ${{ steps.update.outputs.commit }}
          body: 'Automatically generated by https://github.com/xvrh/puppeteer-dart/blob/main/.github/workflows/update-browser-pins.yaml'
          labels: dependencies